import type {
  ProfilePicture,
  Speaker,
} from "@/components/service/contentStrapi";

const profilePhoto = (url: string): ProfilePicture =>
  ({
    url,
  }) as ProfilePicture;

export const pastSpeakers: Speaker[] = [
  {
    id: 1,
    documentId: "past-fabian-bodensteiner",
    name: "Fabian Bodensteiner",
    position: "Managing Director",
    company_name: "World",
    url: "",
    priority: 1,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/fabian-bodensteiner.png"),
  },
  {
    id: 2,
    documentId: "past-paul-brody",
    name: "Paul Brody",
    position: "Global Blockchain Leader",
    company_name: "EY",
    url: "",
    priority: 2,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/paul-brody.png"),
  },
  {
    id: 3,
    documentId: "past-patrick-hansen",
    name: "Patrick Hansen",
    position: "Senior Director, EU Strategy & Policy",
    company_name: "Circle",
    url: "",
    priority: 3,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/patrick-hansen.png"),
  },
  {
    id: 4,
    documentId: "past-jordi-baylina",
    name: "Jordi Baylina",
    position: "Developer",
    company_name: "Zisk",
    url: "",
    priority: 4,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/jordi-baylina.png"),
  },
  {
    id: 5,
    documentId: "past-friederike-ernst",
    name: "Dr. Friederike Ernst",
    position: "Founder",
    company_name: "Gnosis",
    url: "",
    priority: 5,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/friederike-ernst.png"),
  },
  {
    id: 6,
    documentId: "past-justin-drake",
    name: "Justin Drake",
    position: "Researcher",
    company_name: "Ethereum",
    url: "",
    priority: 6,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/justin-drake.png"),
  },
  {
    id: 7,
    documentId: "past-benedikt-buenz",
    name: "Benedikt Bünz",
    position: "Chief Scientist",
    company_name: "Espresso Systems",
    url: "",
    priority: 7,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/placeholder.webp"),
  },
  {
    id: 8,
    documentId: "past-sarah-gramberg",
    name: "Sarah Gramberg",
    position: "PMO",
    company_name: "Digitaler Euro",
    url: "",
    priority: 8,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/past/sarah-gramberg.png"),
  },
  {
    id: 9,
    documentId: "past-kostas-chalkias",
    name: "Kostas Chalkias",
    position: "Chief Cryptographer & Co-Founder",
    company_name: "Sui / Mysten Labs",
    url: "",
    priority: 9,
    createdAt: "",
    updatedAt: "",
    publishedAt: "",
    profile_photo: profilePhoto("/speakers/kostas_chalkias.png"),
  },
];

export const featuredPastSpeakers = pastSpeakers.slice(0, 8);
